In [2]:
import numpy as np
import pandas as pd

In [ ]:
genes_v44=pd.read_csv("/staging/biology/jane0528/NMOSD/scRNA/Dataset/features_v44.tsv",sep='\t',header=None,names=["ENSG","HugoSymbol",'Type']) #My data
genes_v94=pd.read_csv("/staging/biology/jane0528/NMOSD/scRNA/Dataset/Ensembl_v94_ENSG_HUGO.csv",header=None,names=["ENSG","HugoSymbol"]) #GSE164378

In [13]:
genes_v44.drop(columns=['Type'],inplace=True)

In [ ]:
genes_v44 #MY DATA

                  ENSG       HugoSymbol
0      ENSG00000290825          DDX11L2
1      ENSG00000243485      MIR1302-2HG
2      ENSG00000237613          FAM138A
3      ENSG00000290826  ENSG00000290826
4      ENSG00000186092            OR4F5
...                ...              ...
38601  ENSG00000277836  ENSG00000277836
38602  ENSG00000278633  ENSG00000278633
38603  ENSG00000276017  ENSG00000276017
38604  ENSG00000278817  ENSG00000278817
38605  ENSG00000277196  ENSG00000277196

[38606 rows x 2 columns]

In [ ]:
genes_v94 ##GSE164378

                  ENSG  HugoSymbol
0      ENSG00000000003      TSPAN6
1      ENSG00000000005        TNMD
2      ENSG00000000419        DPM1
3      ENSG00000000457       SCYL3
4      ENSG00000000460    C1orf112
...                ...         ...
58730  ENSG00000285990  AL589743.7
58731  ENSG00000285991  AL355312.5
58732  ENSG00000285992  AC120036.5
58733  ENSG00000285993  AC018931.1
58734  ENSG00000285994  AL731559.1

[58735 rows x 2 columns]

In [ ]:
#genecode_v44 和 Ensembl_v94 合併
genes_v44_v94=genes_v94.merge(genes_v44,on='ENSG',how="outer",suffixes=('_v94', '_v44'))
genes_v44_v94

                  ENSG HugoSymbol_v94   HugoSymbol_v44
0      ENSG00000000003         TSPAN6           TSPAN6
1      ENSG00000000005           TNMD             TNMD
2      ENSG00000000419           DPM1             DPM1
3      ENSG00000000457          SCYL3            SCYL3
4      ENSG00000000460       C1orf112         C1orf112
...                ...            ...              ...
62900  ENSG00000292246            NaN  ENSG00000292246
62901  ENSG00000292259            NaN  ENSG00000292259
62902  ENSG00000292271            NaN  ENSG00000292271
62903  ENSG00000292285            NaN  ENSG00000292285
62904  ENSG00000292309            NaN  ENSG00000292309

[62905 rows x 3 columns]

In [ ]:
#genecode_v44 和 Ensembl_v94哪裡不同
diff_genes = genes_v44_v94[genes_v44_v94["HugoSymbol_v94"] != genes_v44_v94["HugoSymbol_v44"]]
diff_genes

                  ENSG HugoSymbol_v94   HugoSymbol_v44
20     ENSG00000002079          MYH16              NaN
88     ENSG00000005238        FAM214B            ATOSB
171    ENSG00000007202       KIAA0100            BLTP2
278    ENSG00000011052      NME1-NME2              NaN
307    ENSG00000011638        TMEM159            LDAF1
...                ...            ...              ...
62900  ENSG00000292246            NaN  ENSG00000292246
62901  ENSG00000292259            NaN  ENSG00000292259
62902  ENSG00000292271            NaN  ENSG00000292271
62903  ENSG00000292285            NaN  ENSG00000292285
62904  ENSG00000292309            NaN  ENSG00000292309

[39921 rows x 3 columns]

In [19]:
# GSE164378 features
reference_genes=pd.read_csv("/staging/biology/jane0528/NMOSD/scRNA/Dataset/GSE164378_features.tsv",sep='\t',header=None,names=["HugoSymbol_v1","HugoSymbol_v2","Gene Expression"])

In [20]:
reference_genes #由表格知第一欄和第二欄一樣

      HugoSymbol_v1 HugoSymbol_v2  Gene Expression
0       MIR1302-2HG   MIR1302-2HG  Gene Expression
1           FAM138A       FAM138A  Gene Expression
2             OR4F5         OR4F5  Gene Expression
3        AL627309.1    AL627309.1  Gene Expression
4        AL627309.3    AL627309.3  Gene Expression
...             ...           ...              ...
33533    AC233755.2    AC233755.2  Gene Expression
33534    AC233755.1    AC233755.1  Gene Expression
33535    AC240274.1    AC240274.1  Gene Expression
33536    AC213203.1    AC213203.1  Gene Expression
33537       FAM231C       FAM231C  Gene Expression

[33538 rows x 3 columns]

In [21]:
reference_genes[reference_genes.duplicated('HugoSymbol_v1', keep=False)] #未有重複

Empty DataFrame
Columns: [HugoSymbol_v1, HugoSymbol_v2, Gene Expression]
Index: []

In [22]:
genes_v44_v94_ref=genes_v44_v94.loc[genes_v44_v94['HugoSymbol_v94'].isin(reference_genes['HugoSymbol_v1']),]
genes_v44_v94_ref

                  ENSG HugoSymbol_v94   HugoSymbol_v44
0      ENSG00000000003         TSPAN6           TSPAN6
1      ENSG00000000005           TNMD             TNMD
2      ENSG00000000419           DPM1             DPM1
3      ENSG00000000457          SCYL3            SCYL3
4      ENSG00000000460       C1orf112         C1orf112
...                ...            ...              ...
58551  ENSG00000285799     AL645929.2              NaN
58636  ENSG00000285887     AL009176.1  ENSG00000285887
58638  ENSG00000285889     AL355312.4              NaN
58721  ENSG00000285980     AP003025.2  ENSG00000285980
58726  ENSG00000285986     BX248415.1              NaN

[33270 rows x 3 columns]

In [23]:
#genecode_v44 和 Ensembl_v94_ref哪裡不同
diff_genes_with_ref = genes_v44_v94_ref[genes_v44_v94_ref["HugoSymbol_v94"] != genes_v44_v94_ref["HugoSymbol_v44"]]
diff_genes_with_ref

                  ENSG HugoSymbol_v94   HugoSymbol_v44
88     ENSG00000005238        FAM214B            ATOSB
171    ENSG00000007202       KIAA0100            BLTP2
278    ENSG00000011052      NME1-NME2              NaN
307    ENSG00000011638        TMEM159            LDAF1
349    ENSG00000014257           ACPP             ACP3
...                ...            ...              ...
58551  ENSG00000285799     AL645929.2              NaN
58636  ENSG00000285887     AL009176.1  ENSG00000285887
58638  ENSG00000285889     AL355312.4              NaN
58721  ENSG00000285980     AP003025.2  ENSG00000285980
58726  ENSG00000285986     BX248415.1              NaN

[10828 rows x 3 columns]

In [24]:
#建新欄位"HugoSymbol_merge"，以v44為主，若為NaN -> ENSG取代
genes_v44_v94_ref["HugoSymbol_merge"] = np.where(
    genes_v44_v94_ref["HugoSymbol_v44"].notna(),
    genes_v44_v94_ref["HugoSymbol_v44"],
    genes_v44_v94_ref["ENSG"]
)

/tmp/ipykernel_1169994/2739287765.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  genes_v44_v94_ref["HugoSymbol_merge"] = np.where(

In [25]:
genes_v44_v94_ref

                  ENSG HugoSymbol_v94   HugoSymbol_v44 HugoSymbol_merge
0      ENSG00000000003         TSPAN6           TSPAN6           TSPAN6
1      ENSG00000000005           TNMD             TNMD             TNMD
2      ENSG00000000419           DPM1             DPM1             DPM1
3      ENSG00000000457          SCYL3            SCYL3            SCYL3
4      ENSG00000000460       C1orf112         C1orf112         C1orf112
...                ...            ...              ...              ...
58551  ENSG00000285799     AL645929.2              NaN  ENSG00000285799
58636  ENSG00000285887     AL009176.1  ENSG00000285887  ENSG00000285887
58638  ENSG00000285889     AL355312.4              NaN  ENSG00000285889
58721  ENSG00000285980     AP003025.2  ENSG00000285980  ENSG00000285980
58726  ENSG00000285986     BX248415.1              NaN  ENSG00000285986

[33270 rows x 4 columns]

In [26]:
#取 v94唯一的hugo symbols
genes_v44_v94_ref_unique = genes_v44_v94_ref[
    ~genes_v44_v94_ref["HugoSymbol_v94"].duplicated(keep=False)
].reset_index(drop=True)
genes_v44_v94_ref_unique

                  ENSG HugoSymbol_v94   HugoSymbol_v44 HugoSymbol_merge
0      ENSG00000000003         TSPAN6           TSPAN6           TSPAN6
1      ENSG00000000005           TNMD             TNMD             TNMD
2      ENSG00000000419           DPM1             DPM1             DPM1
3      ENSG00000000457          SCYL3            SCYL3            SCYL3
4      ENSG00000000460       C1orf112         C1orf112         C1orf112
...                ...            ...              ...              ...
33187  ENSG00000285799     AL645929.2              NaN  ENSG00000285799
33188  ENSG00000285887     AL009176.1  ENSG00000285887  ENSG00000285887
33189  ENSG00000285889     AL355312.4              NaN  ENSG00000285889
33190  ENSG00000285980     AP003025.2  ENSG00000285980  ENSG00000285980
33191  ENSG00000285986     BX248415.1              NaN  ENSG00000285986

[33192 rows x 4 columns]

In [27]:
genes_v44_v94_ref_unique.to_csv("/staging/biology/jane0528/NMOSD/scRNA/Dataset/genes_v44_v94_ref_merged(unique).csv",index=None)

In [28]:
genes_v44_v94_ref.to_csv("/staging/biology/jane0528/NMOSD/scRNA/Dataset/genes_v32_v94_ref_merged.csv",index=None)

In [29]:
genes_v44_v94_ref_dup=genes_v44_v94_ref[genes_v44_v94_ref.duplicated('HugoSymbol_v94', keep=False)] #未有重複
genes_v44_v94_ref_dup

                  ENSG HugoSymbol_v94   HugoSymbol_v44 HugoSymbol_merge
360    ENSG00000015479          MATR3            MATR3            MATR3
3999   ENSG00000112096           SOD2              NaN  ENSG00000112096
4282   ENSG00000114395       CYB561D2         CYB561D2         CYB561D2
6056   ENSG00000128655         PDE11A           PDE11A           PDE11A
6272   ENSG00000130489           SCO2              NaN  ENSG00000130489
...                ...            ...              ...              ...
58201  ENSG00000285258          ATXN7              NaN  ENSG00000285258
58249  ENSG00000285437        POLR2J3          POLR2J3          POLR2J3
58250  ENSG00000285441           SOD2              NaN  ENSG00000285441
58254  ENSG00000285447         ZNF883              NaN  ENSG00000285447
58275  ENSG00000285517      LINC00941  ENSG00000285517  ENSG00000285517

[78 rows x 4 columns]

In [30]:
genes_v44_v94_ref_dup_sort = genes_v44_v94_ref_dup.sort_values(by="HugoSymbol_v94").reset_index(drop=True)
genes_v44_v94_ref_dup_sort

               ENSG HugoSymbol_v94   HugoSymbol_v44 HugoSymbol_merge
0   ENSG00000163635          ATXN7            ATXN7            ATXN7
1   ENSG00000285258          ATXN7              NaN  ENSG00000285258
2   ENSG00000145075         CCDC39              NaN  ENSG00000145075
3   ENSG00000284862         CCDC39           CCDC39           CCDC39
4   ENSG00000271858       CYB561D2  ENSG00000271858  ENSG00000271858
..              ...            ...              ...              ...
73  ENSG00000158427        TMSB15B          TMSB15B          TMSB15B
74  ENSG00000165655         ZNF503           ZNF503           ZNF503
75  ENSG00000270087         ZNF503  ENSG00000270087  ENSG00000270087
76  ENSG00000228623         ZNF883           ZNF883           ZNF883
77  ENSG00000285447         ZNF883              NaN  ENSG00000285447

[78 rows x 4 columns]

In [32]:
#若v44和v94一樣 -> 保留其一
genes_v44_v94_ref_dup_sort_v2 = (
    genes_v44_v94_ref_dup_sort.drop_duplicates(
        subset=["HugoSymbol_v94", "HugoSymbol_v44"],
        keep="first"
    )
    .reset_index(drop=True)
)

In [33]:
genes_v44_v94_ref_dup_sort_v2

               ENSG HugoSymbol_v94   HugoSymbol_v44 HugoSymbol_merge
0   ENSG00000163635          ATXN7            ATXN7            ATXN7
1   ENSG00000285258          ATXN7              NaN  ENSG00000285258
2   ENSG00000145075         CCDC39              NaN  ENSG00000145075
3   ENSG00000284862         CCDC39           CCDC39           CCDC39
4   ENSG00000271858       CYB561D2  ENSG00000271858  ENSG00000271858
..              ...            ...              ...              ...
62  ENSG00000158427        TMSB15B          TMSB15B          TMSB15B
63  ENSG00000165655         ZNF503           ZNF503           ZNF503
64  ENSG00000270087         ZNF503  ENSG00000270087  ENSG00000270087
65  ENSG00000228623         ZNF883           ZNF883           ZNF883
66  ENSG00000285447         ZNF883              NaN  ENSG00000285447

[67 rows x 4 columns]

In [34]:
#去除Nan
genes_v44_v94_ref_dup_sort_v3 = genes_v44_v94_ref_dup_sort_v2.dropna()

In [35]:
genes_v44_v94_ref_dup_sort_v3

               ENSG HugoSymbol_v94   HugoSymbol_v44 HugoSymbol_merge
0   ENSG00000163635          ATXN7            ATXN7            ATXN7
3   ENSG00000284862         CCDC39           CCDC39           CCDC39
4   ENSG00000271858       CYB561D2  ENSG00000271858  ENSG00000271858
5   ENSG00000114395       CYB561D2         CYB561D2         CYB561D2
6   ENSG00000184047         DIABLO           DIABLO           DIABLO
7   ENSG00000284934         DIABLO  ENSG00000284934  ENSG00000284934
8   ENSG00000227540     DNAJC9-AS1       DNAJC9-AS1       DNAJC9-AS1
9   ENSG00000166897          ELFN2            ELFN2            ELFN2
10  ENSG00000261480        GOLGA8M          GOLGA8M          GOLGA8M
11  ENSG00000234289          H2BFS          H2BC12L          H2BC12L
14  ENSG00000172789          HOXC5            HOXC5            HOXC5
15  ENSG00000284024         HSPA14          MSANTD7          MSANTD7
16  ENSG00000187522         HSPA14           HSPA14           HSPA14
17  ENSG00000167244           IGF2             IGF2             IGF2
18  ENSG00000284779           IGF2  ENSG00000284779  ENSG00000284779
19  ENSG00000258325      ITFG2-AS1        ITFG2-AS1        ITFG2-AS1
22  ENSG00000253696    KBTBD11-OT1      KBTBD11-OT1      KBTBD11-OT1
23  ENSG00000235641      LINC00484        LINC00484        LINC00484
24  ENSG00000285517      LINC00941  ENSG00000285517  ENSG00000285517
26  ENSG00000272342      LINC01115        LINC01115        LINC01115
27  ENSG00000261186      LINC01238        LINC01238        LINC01238
28  ENSG00000225255      LINC01297            PSLNR            PSLNR
29  ENSG00000274827      LINC01297        LINC01297        LINC01297
30  ENSG00000223704      LINC01422        LINC01422        LINC01422
31  ENSG00000235271      LINC01422  ENSG00000235271  ENSG00000235271
32  ENSG00000257815      LINC01481           PRANCR           PRANCR
34  ENSG00000234323      LINC01505        LINC01505        LINC01505
37  ENSG00000284988      LINC02203        LINC02203        LINC02203
39  ENSG00000015479          MATR3            MATR3            MATR3
40  ENSG00000128655         PDE11A           PDE11A           PDE11A
42  ENSG00000254093          PINX1            PINX1            PINX1
44  ENSG00000285437        POLR2J3          POLR2J3          POLR2J3
46  ENSG00000241572   PRICKLE2-AS1     PRICKLE2-AS1     PRICKLE2-AS1
48  ENSG00000283706         PRSS50           PRSS50           PRSS50
49  ENSG00000223701     RAET1E-AS1       RAET1E-AS1       RAET1E-AS1
50  ENSG00000232995           RGS5  ENSG00000232995  ENSG00000232995
51  ENSG00000143248           RGS5             RGS5             RGS5
53  ENSG00000284194           SCO2             SCO2             SCO2
55  ENSG00000188004         SNHG28           SNHG28           SNHG28
58  ENSG00000182957        SPATA13          SPATA13          SPATA13
59  ENSG00000284770           TBCE             TBCE             TBCE
61  ENSG00000269226        TMSB15B          TMSB15C          TMSB15C
62  ENSG00000158427        TMSB15B          TMSB15B          TMSB15B
63  ENSG00000165655         ZNF503           ZNF503           ZNF503
64  ENSG00000270087         ZNF503  ENSG00000270087  ENSG00000270087
65  ENSG00000228623         ZNF883           ZNF883           ZNF883

In [36]:
genes_v44_v94_ref_dup_sort_v3.to_csv("/staging/biology/jane0528/NMOSD/scRNA/Dataset/genes_v44_v94_ref_merged(duplicated).csv",index=None)
#要在手動去除

In [37]:
genes_v44_v94_ref_dup_clean=pd.read_csv('/staging/biology/jane0528/NMOSD/scRNA/Dataset/genes_v44_v94_ref_merged(duplicated_cleaned).csv')
genes_v44_v94_ref_dup_clean

               ENSG HugoSymbol_v94   HugoSymbol_v44 HugoSymbol_merge
0   ENSG00000163635          ATXN7            ATXN7            ATXN7
1   ENSG00000284862         CCDC39           CCDC39           CCDC39
2   ENSG00000114395       CYB561D2         CYB561D2         CYB561D2
3   ENSG00000184047         DIABLO           DIABLO           DIABLO
4   ENSG00000227540     DNAJC9-AS1       DNAJC9-AS1       DNAJC9-AS1
5   ENSG00000166897          ELFN2            ELFN2            ELFN2
6   ENSG00000261480        GOLGA8M          GOLGA8M          GOLGA8M
7   ENSG00000234289          H2BFS          H2BC12L          H2BC12L
8   ENSG00000172789          HOXC5            HOXC5            HOXC5
9   ENSG00000187522         HSPA14           HSPA14           HSPA14
10  ENSG00000167244           IGF2             IGF2             IGF2
11  ENSG00000258325      ITFG2-AS1        ITFG2-AS1        ITFG2-AS1
12  ENSG00000253696    KBTBD11-OT1      KBTBD11-OT1      KBTBD11-OT1
13  ENSG00000235641      LINC00484        LINC00484        LINC00484
14  ENSG00000285517      LINC00941  ENSG00000285517  ENSG00000285517
15  ENSG00000272342      LINC01115        LINC01115        LINC01115
16  ENSG00000261186      LINC01238        LINC01238        LINC01238
17  ENSG00000274827      LINC01297        LINC01297        LINC01297
18  ENSG00000223704      LINC01422        LINC01422        LINC01422
19  ENSG00000257815      LINC01481           PRANCR           PRANCR
20  ENSG00000234323      LINC01505        LINC01505        LINC01505
21  ENSG00000284988      LINC02203        LINC02203        LINC02203
22  ENSG00000015479          MATR3            MATR3            MATR3
23  ENSG00000128655         PDE11A           PDE11A           PDE11A
24  ENSG00000254093          PINX1            PINX1            PINX1
25  ENSG00000285437        POLR2J3          POLR2J3          POLR2J3
26  ENSG00000241572   PRICKLE2-AS1     PRICKLE2-AS1     PRICKLE2-AS1
27  ENSG00000283706         PRSS50           PRSS50           PRSS50
28  ENSG00000223701     RAET1E-AS1       RAET1E-AS1       RAET1E-AS1
29  ENSG00000143248           RGS5             RGS5             RGS5
30  ENSG00000284194           SCO2             SCO2             SCO2
31  ENSG00000188004         SNHG28           SNHG28           SNHG28
32  ENSG00000182957        SPATA13          SPATA13          SPATA13
33  ENSG00000284770           TBCE             TBCE             TBCE
34  ENSG00000158427        TMSB15B          TMSB15B          TMSB15B
35  ENSG00000165655         ZNF503           ZNF503           ZNF503
36  ENSG00000228623         ZNF883           ZNF883           ZNF883

In [38]:
#確保 v94未有重複
genes_v44_v94_ref_dup_clean[genes_v44_v94_ref_dup_clean.duplicated('HugoSymbol_v94',keep=False)]

Empty DataFrame
Columns: [ENSG, HugoSymbol_v94, HugoSymbol_v44, HugoSymbol_merge]
Index: []

In [39]:
unique_genes_map=pd.read_csv("/staging/biology/jane0528/NMOSD/scRNA/Dataset/genes_v44_v94_ref_merged(unique).csv")
dup_genes_map=pd.read_csv("/staging/biology/jane0528/NMOSD/scRNA/Dataset/genes_v44_v94_ref_merged(duplicated_cleaned).csv")

In [40]:
unique_genes_map

                  ENSG HugoSymbol_v94   HugoSymbol_v44 HugoSymbol_merge
0      ENSG00000000003         TSPAN6           TSPAN6           TSPAN6
1      ENSG00000000005           TNMD             TNMD             TNMD
2      ENSG00000000419           DPM1             DPM1             DPM1
3      ENSG00000000457          SCYL3            SCYL3            SCYL3
4      ENSG00000000460       C1orf112         C1orf112         C1orf112
...                ...            ...              ...              ...
33187  ENSG00000285799     AL645929.2              NaN  ENSG00000285799
33188  ENSG00000285887     AL009176.1  ENSG00000285887  ENSG00000285887
33189  ENSG00000285889     AL355312.4              NaN  ENSG00000285889
33190  ENSG00000285980     AP003025.2  ENSG00000285980  ENSG00000285980
33191  ENSG00000285986     BX248415.1              NaN  ENSG00000285986

[33192 rows x 4 columns]

In [41]:
dup_genes_map

               ENSG HugoSymbol_v94   HugoSymbol_v44 HugoSymbol_merge
0   ENSG00000163635          ATXN7            ATXN7            ATXN7
1   ENSG00000284862         CCDC39           CCDC39           CCDC39
2   ENSG00000114395       CYB561D2         CYB561D2         CYB561D2
3   ENSG00000184047         DIABLO           DIABLO           DIABLO
4   ENSG00000227540     DNAJC9-AS1       DNAJC9-AS1       DNAJC9-AS1
5   ENSG00000166897          ELFN2            ELFN2            ELFN2
6   ENSG00000261480        GOLGA8M          GOLGA8M          GOLGA8M
7   ENSG00000234289          H2BFS          H2BC12L          H2BC12L
8   ENSG00000172789          HOXC5            HOXC5            HOXC5
9   ENSG00000187522         HSPA14           HSPA14           HSPA14
10  ENSG00000167244           IGF2             IGF2             IGF2
11  ENSG00000258325      ITFG2-AS1        ITFG2-AS1        ITFG2-AS1
12  ENSG00000253696    KBTBD11-OT1      KBTBD11-OT1      KBTBD11-OT1
13  ENSG00000235641      LINC00484        LINC00484        LINC00484
14  ENSG00000285517      LINC00941  ENSG00000285517  ENSG00000285517
15  ENSG00000272342      LINC01115        LINC01115        LINC01115
16  ENSG00000261186      LINC01238        LINC01238        LINC01238
17  ENSG00000274827      LINC01297        LINC01297        LINC01297
18  ENSG00000223704      LINC01422        LINC01422        LINC01422
19  ENSG00000257815      LINC01481           PRANCR           PRANCR
20  ENSG00000234323      LINC01505        LINC01505        LINC01505
21  ENSG00000284988      LINC02203        LINC02203        LINC02203
22  ENSG00000015479          MATR3            MATR3            MATR3
23  ENSG00000128655         PDE11A           PDE11A           PDE11A
24  ENSG00000254093          PINX1            PINX1            PINX1
25  ENSG00000285437        POLR2J3          POLR2J3          POLR2J3
26  ENSG00000241572   PRICKLE2-AS1     PRICKLE2-AS1     PRICKLE2-AS1
27  ENSG00000283706         PRSS50           PRSS50           PRSS50
28  ENSG00000223701     RAET1E-AS1       RAET1E-AS1       RAET1E-AS1
29  ENSG00000143248           RGS5             RGS5             RGS5
30  ENSG00000284194           SCO2             SCO2             SCO2
31  ENSG00000188004         SNHG28           SNHG28           SNHG28
32  ENSG00000182957        SPATA13          SPATA13          SPATA13
33  ENSG00000284770           TBCE             TBCE             TBCE
34  ENSG00000158427        TMSB15B          TMSB15B          TMSB15B
35  ENSG00000165655         ZNF503           ZNF503           ZNF503
36  ENSG00000228623         ZNF883           ZNF883           ZNF883

In [42]:
genes_v44_v94_concat = pd.concat([unique_genes_map, dup_genes_map], axis=0).reset_index(drop=True)

In [43]:
genes_v44_v94_concat

                  ENSG HugoSymbol_v94 HugoSymbol_v44 HugoSymbol_merge
0      ENSG00000000003         TSPAN6         TSPAN6           TSPAN6
1      ENSG00000000005           TNMD           TNMD             TNMD
2      ENSG00000000419           DPM1           DPM1             DPM1
3      ENSG00000000457          SCYL3          SCYL3            SCYL3
4      ENSG00000000460       C1orf112       C1orf112         C1orf112
...                ...            ...            ...              ...
33224  ENSG00000182957        SPATA13        SPATA13          SPATA13
33225  ENSG00000284770           TBCE           TBCE             TBCE
33226  ENSG00000158427        TMSB15B        TMSB15B          TMSB15B
33227  ENSG00000165655         ZNF503         ZNF503           ZNF503
33228  ENSG00000228623         ZNF883         ZNF883           ZNF883

[33229 rows x 4 columns]

In [44]:
genes_v44_v94_concat.to_csv("/staging/biology/jane0528/NMOSD/scRNA/Dataset/GSE164378_v94_to_v44.csv",index=False)

In [46]:
mapping_df=pd.read_csv("/staging/biology/jane0528/NMOSD/scRNA/Dataset/GSE164378_v94_to_v44.csv")
mapping_dict = dict(zip(mapping_df["HugoSymbol_v94"], mapping_df["HugoSymbol_merge"]))

In [47]:
#讀取 GSE164378 features.tsv.gz
features = pd.read_csv("/staging/biology/jane0528/NMOSD/scRNA/Dataset/GSE164378_features.tsv", sep="\t", header=None, names=["HUGO1", "HUGO2", "TYPE"])
print("原始 features 行數:", len(features))

# 替換
features["HUGO1"] = features["HUGO1"].map(mapping_dict).fillna(features["HUGO1"])
features["HUGO2"] = features["HUGO2"].map(mapping_dict).fillna(features["HUGO2"])

原始 features 行數: 33538

In [48]:
# 輸出新的 features 檔案
features.to_csv("/staging/biology/jane0528/NMOSD/scRNA/Dataset/GSE164378_features_renamed(v44).tsv", sep="\t", index=False, header=False)